Home page at mobile, only HTML, without CSS
eagleas/fcourse pull request #1
Opened 2023-04-12 10:28 UTC by eagleas

2023-04-13 16:37 UTC, shashkovdanil requested changes

2023-04-13 16:37 UTC, shashkovdanil commented on index.html
> +        <img width="36" src="assets/cart.svg" alt="Cart">&nbsp;Cart
Иконка корзины это обычно ссылка на страницу /cart

2023-04-13 16:37 UTC, shashkovdanil commented on index.html
> +      <h1 align="center">Make their <font style="font-family: Yesteryear;" color="#D476F8">day extra special</font> with a handcrafted bouquet.</h1>
Нужно убрать тэг фонт и все стили которые прописаны в html

2023-04-13 16:37 UTC, shashkovdanil commented on index.html
> +        <figure>
Это должна быть ссылка на товар

2023-04-13 16:37 UTC, shashkovdanil commented on index.html
> +      <div><img height="80" src="assets/logo.svg" alt="FLoweLowe Logo"></div>
Логотип это ссылка на страницу

2023-04-13 16:37 UTC, shashkovdanil commented on index.html
> +        <ul>
Тут тоже все должно быть ссылками

2023-04-20 16:48 UTC, eagleas reviewed
Изменения были внесены.

2023-04-20 16:49 UTC, merged